apiVersion: v1
kind: Service
metadata:
  name: example-service
spec:
  selector:
    app.kubernetes.io/name: MyApp
  ports:
    - name: http
      protocol: TCP
      port: 3000
      targetPort: 3000