apiVersion: v1
kind: Service
metadata:
  name: example_app-service
spec:
  selector:
    app.kubernetes.io/name: MyApp
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 3000