apiVersion: v1
kind: Service
metadata:
  name: example-service
spec:
  type: LoadBalancer
  selector:
    app: example-app
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 3000